# Open folder in PowerShell
# Enter: docker-compose up -d
# https://wiki.ayanev.eu/#/do-it-yourself/2023-01-home-media-server/
# https://www.reddit.com/r/unRAID/comments/180ou0b/psa_if_you_cant_login_to_qbittorrent_pass/

# [xh.]?[._-]?(265)|(HEVC)

version: "3.9"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - HOSTNAME=”PlexServer”
    volumes:
      - C:\Containers\provision\plex:/config
      - C:\Containers\content\media:/data/media
    ports:
      - "32400:32400/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    privileged: true
    restart: unless-stopped
  overseerr:
    image: linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - C:\Containers\provision\overseerr\config:/config
    ports:
      - 5055:5055
    restart: unless-stopped
  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - C:\Containers\provision\prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - media-network
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - C:\Containers\provision\Radarr:/config
      - C:\Containers\content:/data
    ports:
      - "7878:7878"
    restart: unless-stopped
    networks:
      - media-network
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - C:\Containers\provision\Sonarr:/config
      - C:\Containers\content:/data
    ports:
      - "8989:8989"
    restart: unless-stopped
    networks:
      - media-network
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - C:\Containers\provision\bazarr:/config
      - C:\Containers\content:/data
    ports:
      - "6767:6767"
    restart: unless-stopped
    networks:
      - media-network
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - C:\Containers\provision\qbittorrent:/config
      - C:\Containers\content\torrents:/data/torrents
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - media-network
networks:
  media-network:
